/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b8c4ff",
        "on-tertiary": "#ffffff",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed": "#002113",
        "outline-variant": "#c4c5d5",
        "outline": "#757684",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#001453",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#802a00",
        "on-primary-fixed-variant": "#173bab",
        "tertiary-container": "#872d00",
        "surface": "#f8f9ff",
        "primary-container": "#1e40af",
        "error": "#ba1a1a",
        "tertiary": "#611e00",
        "tertiary-fixed-dim": "#ffb59a",
        "tertiary-fixed": "#ffdbce",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "primary": "#00288e",
        "on-error": "#ffffff",
        "surface-tint": "#3755c3",
        "primary-fixed-dim": "#b8c4ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#005236",
        "secondary": "#006c49",
        "on-tertiary-fixed": "#380d00",
        "surface-dim": "#cbdbf5",
        "on-tertiary-container": "#ffa583",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#444653",
        "surface-container-low": "#eff4ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "on-primary-container": "#a8b8ff",
        "inverse-surface": "#213145"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "base": "4px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "24px",
        "md": "16px",
        "xs": "4px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "body-sm": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
